"""Full prod document-type label table for the visit-summary allowlist (v2) -- labels ONLY.

Source: the 147 distinct production document-type labels pulled 2026-10-07 (labels only; counts
are not stored here, no ids/PHI). Each row: (normalized_label, expected_eligible,
expected_include_rule_id, expected_deny_rule_id). The empty label is the NULL/empty-type bucket.
Decisions were reviewed against FINAL-PLAN s1.2 (decision rule) and the s1.5 veto table:
34 labels eligible, 113 not.

Seven borderline long-tail labels are deliberately EXCLUDED (``er depart documentation-form``,
``*postop report``, ``*preoperative report``, ``emergency room record``, ``provider documentation``,
``post-op transfer/handoff note``, ``surgical documents``). They are excluded by the default rule
(no include match), NOT by a deny rule, and are tracked by the label watch / owner review.

The earlier prod-named subset in ``visit_summary_allowlist_labels.py`` (PROD_NAMED_LABELS, 56
non-NULL labels) is NOT a strict subset: 50 are in this table (asserted identical by the T0 test);
6 named in the research are absent from the pull (``op note - complete``, ``operative note``,
``follow up note``, ``nursing narrative note``, ``ed note nursing``, ``transfer note``) and are kept
as extra pins (PROD_NAMED_ONLY) in the T0 table.
"""

PROD_LABEL_ROWS = (
    ("encounter summary", True, "vs.summary", None),
    ("history and physical", True, "note.hp", None),
    ("progress notes", True, "note.progress", None),
    ("telephone encounter", True, "note.telephone", None),
    ("diagnostic imaging study", False, None, "deny.diagnostic"),
    ("patient instructions", False, None, "deny.instructions"),
    ("ccd document", True, "vs.ccd", None),
    ("laboratory report", False, None, "deny.diagnostic"),
    ("phone msg", False, None, None),
    ("lab report", False, None, "deny.diagnostic"),
    ("insurance", False, None, None),
    ("patient education document", False, None, "deny.education"),
    ("discharge instructions", False, None, "deny.instructions"),
    ("", False, None, None),
    ("practice intake and history - form", False, None, None),
    ("ed notes", True, "note.ed", None),
    ("imaging report", False, None, "deny.diagnostic"),
    ("patient summary", True, "vs.summary", None),
    ("primary care office note", True, "note.office_clinic", None),
    ("consent to discuss care & treatment", False, None, None),
    ("pre-cert information - form", False, None, None),
    ("annual consent for treatment", False, None, None),
    ("h&p", True, "note.hp_abbrev", None),
    ("urgent care office clinic note", True, "note.office_clinic", None),
    ("anesthesia postprocedure evaluation", False, None, "deny.anesthesia"),
    ("anesthesia preprocedure evaluation", False, None, "deny.anesthesia"),
    ("bariatric intake and history-form", False, None, None),
    ("uc intake and history (practice) - form", False, None, None),
    ("bariatric surgery office visit note", True, "note.office_clinic", None),
    ("nursing note", False, None, "deny.nursing"),
    ("practice visit summary", True, "vs.summary", None),
    ("acknowledgments", False, None, None),
    ("anesthesia procedure notes", False, "note.operative", "deny.anesthesia"),
    ("discharge summary", True, "vs.summary", None),
    ("ed provider notes", True, "note.ed", None),
    ("*history & physical", True, "note.hp", None),
    ("op note", True, "note.operative", None),
    ("plan of care", False, None, None),
    ("practice clinical summary", True, "vs.summary", None),
    ("practice patient summary", True, "vs.summary", None),
    ("anesthesiologist pre-procedure attestation", False, None, "deny.anesthesia"),
    ("consent surgery/procedure", False, None, None),
    ("or surgeon", False, None, None),
    ("*preoperative report", False, None, None),
    ("result encounter note", False, None, None),
    ("uc follow-up phone call to pt - form", True, "note.telephone", None),
    ("upper gi endo report", True, "note.operative", None),
    ("admit nsg note", False, None, "deny.nursing"),
    ("anesthesia electronic record", False, None, "deny.anesthesia"),
    ("anesthesia preop eval", False, None, "deny.anesthesia"),
    ("consent documents", False, None, None),
    ("d/c nursing note", False, None, "deny.nursing"),
    ("discharge instruction", False, None, "deny.instructions"),
    ("ed clinical summary", True, "vs.summary", None),
    ("ed patient education note", False, None, "deny.education"),
    ("ed patient summary", True, "vs.summary", None),
    ("emergency room record", False, None, None),
    ("encounter cover page", False, None, None),
    ("er depart documentation-form", False, None, None),
    ("er vitals and ht/wt", False, None, None),
    ("facesheet", False, None, None),
    ("intraoperative report", False, None, None),
    ("know your numbers form", False, None, None),
    ("other", False, None, None),
    ("patient letter", False, None, None),
    ("post anesthesia record", False, None, "deny.anesthesia"),
    ("*postop report", False, None, None),
    ("preprocedure intake - text", False, None, "deny.text_rendering"),
    ("provider documentation", False, None, None),
    ("surgical documents", False, None, None),
    ("anesthesiologist pre-procedure chart review", False, None, "deny.anesthesia"),
    ("bh message", False, None, None),
    ("cdu treatment plan", False, None, None),
    ("certification id", False, None, None),
    ("consults", True, "note.consult", None),
    ("discharge information-form", False, None, None),
    ("ed intake - adult hsed ecd-form", False, None, None),
    ("ekg.", False, None, "deny.diagnostic"),
    ("er family notification of admission-form", False, None, None),
    ("external authorizations", False, None, None),
    ("inpatient clinical summary", True, "vs.summary", None),
    ("inpatient patient summary", True, "vs.summary", None),
    ("interval h&p note", True, "note.hp_abbrev", None),
    ("laboratory report narrative", False, None, "deny.diagnostic"),
    ("masked", False, None, None),
    ("op note - complete (template or full dictation)", True, "note.operative", None),
    ("perioperative nursing note", False, None, "deny.nursing"),
    ("post-op transfer/handoff note", False, None, None),
    ("pre visit planning note (practice) form", False, None, None),
    ("procedures", False, None, None),
    ("provider's discharge instructions-form", False, None, "deny.instructions"),
    ("ra upper gi w/ kub", False, None, None),
    ("spf", False, None, None),
    ("sw follow up note", True, "note.follow_up", None),
    ("ambulatory clinic vital signs", False, None, None),
    ("bariatric nutrition assessment - form", False, None, None),
    ("basic admission information-form", False, None, None),
    ("basic intake information-form", False, None, None),
    ("bravo report", False, None, None),
    ("cardiac diag charge-form", False, None, None),
    ("cdu sw dc instructions", False, None, "deny.instructions"),
    (
        "cdu sw level of care transition/discharge plan instructions",
        False,
        None,
        "deny.instructions",
    ),
    ("cm phone msg", False, None, None),
    ("ct head or brain w/o contrast", False, None, "deny.diagnostic"),
    ("disability form", False, None, None),
    ("*discharge summary", True, "vs.summary", None),
    ("ed intake adult ecd-form", False, None, None),
    ("ed triage adult ecd-form", False, None, None),
    ("er family notified of hospital stay-form", False, None, None),
    ("error", False, None, None),
    ("er triage - ekg", False, None, "deny.diagnostic"),
    ("external document (ccd)", True, "vs.ccd", None),
    ("external prescription", False, None, None),
    ("external scheduling form", False, None, None),
    ("external ultrasound", False, None, "deny.diagnostic"),
    ("gynecology office note", True, "note.office_clinic", None),
    ("history adult-form", False, None, None),
    ("infection control", False, None, None),
    ("ip initial certification", False, None, None),
    ("mri brain w/wo contrast", False, None, "deny.diagnostic"),
    ("mri spine lumbar w/o contrast", False, None, "deny.diagnostic"),
    ("nm hepatobiliary sys image w/drug", False, None, None),
    ("nursing note-form", False, None, "deny.nursing"),
    ("operative report", True, "note.operative", None),
    ("pat adult telephone interviewecd-form", False, None, None),
    ("perioperative education-text", False, None, "deny.text_rendering"),
    ("physician order", False, None, None),
    ("poc rapid infuenza - form", False, None, None),
    ("poc rapid strep - form", False, None, None),
    ("poc urine dipstick and microscopy - form", False, None, None),
    ("practice more vitals/measurement", False, None, None),
    ("preop surgical preparation-form", False, None, None),
    ("pre-procedure instructions", False, None, "deny.instructions"),
    ("procedure note", True, "note.operative", None),
    ("*progress note", True, "note.progress", None),
    ("pt health questionnaire/phq9-form", False, None, None),
    ("ra chest 1 view frontal", False, None, None),
    ("ra chest 2 views", False, None, None),
    ("release of information", False, None, None),
    ("reportability response - public health", False, None, None),
    ("transfer receiving (raamps)-form", False, None, None),
    ("urgent care lab log sheet", False, None, "deny.diagnostic"),
    ("urgent care radiology qa", False, None, "deny.diagnostic"),
    ("us venous leg left", False, None, None),
    ("wellness exam certification", False, None, None),
    ("wh electronic pap smear log - form", False, None, None),
    ("women's health intake & history-form", False, None, None),
)
