"""T0 label table for the visit-summary allowlist (v2) -- labels ONLY, no ids/PHI.

Each row: (env, normalized_label_or_None, expected_eligible, expected_include_rule_id, expected_deny_rule_id).

* ``expected_eligible`` is the INDEPENDENT hand decision taken from FINAL-PLAN s1.3/s1.5 (the
  per-type veto table), not derived from ``match()``.
* the rule ids are a regression pin of the first matching include / deny rule.
* DEV (108 rows) is the complete distinct-label list of the round-1 dev census
  (``round1-census-data.md`` A1). PROD rows are every prod label NAMED in the research
  (``round2-prod-census.md`` s2.2/s2.3/s3 and FINAL-PLAN s1.3/s1.5). The full 147-label prod
  distinct list was pulled once into a local file that was never checked in (FINAL-PLAN s0, "kept
  in a local file") and is not reproducible from the research files, so only the named subset is
  pinned here; unnamed prod labels fall in the n<5 long tail.
"""

LABEL_TABLE = (
    ('dev', 'plan of care', False, None, None),
    ('dev', 'consultation note generic', True, 'note.consult', None),
    ('dev', 'rheumatology consultation', True, 'note.consult', None),
    ('dev', 'telemedicine consultation', True, 'note.telehealth', None),
    ('dev', 'cardiology consultation', True, 'note.consult', None),
    ('dev', 'orthopedic consultation', True, 'note.consult', None),
    ('dev', 'trauma consultation', True, 'note.consult', None),
    ('dev', 'gynecology consultation', True, 'note.consult', None),
    ('dev', 'ed note physician', True, 'note.ed', None),
    ('dev', 'hospital course documentation', True, 'vs.hospital_course', None),
    ('dev', 'admission note physician', True, 'note.admission', None),
    ('dev', 'history and physical', True, 'note.hp', None),
    ('dev', 'h&p', True, 'note.hp_abbrev', None),
    ('dev', 'discharge instructions', False, None, 'deny.instructions'),
    ('dev', 'inpatient discharge instructions', False, None, 'deny.instructions'),
    ('dev', 'ambulatory visit instructions', False, None, 'deny.instructions'),
    ('dev', 'patient instructions', False, None, 'deny.instructions'),
    ('dev', 'amb med review add', False, None, None),
    ('dev', 'ed note nursing', False, 'note.ed', 'deny.note_nursing'),
    ('dev', 'nursing narrative note', False, None, 'deny.nursing'),
    ('dev', 'discharge note nursing', False, None, 'deny.note_nursing'),
    ('dev', 'operative report', True, 'note.operative', None),
    ('dev', 'procedure note', True, 'note.operative', None),
    ('dev', 'anesthesia preoperative evaluation', False, None, 'deny.anesthesia'),
    ('dev', 'op note', True, 'note.operative', None),
    ('dev', 'allergy / immunology clinic procedure', False, None, None),
    ('dev', 'operative note', True, 'note.operative', None),
    ('dev', 'main or intraoperative record', False, None, None),
    ('dev', 'patient summary', True, 'vs.summary', None),
    ('dev', 'pregnancy summary document', False, None, None),
    ('dev', 'patient conversation', False, None, None),
    ('dev', 'phone msg', False, None, None),
    ('dev', 'height weight allergy rule - text', False, None, 'deny.text_rendering'),
    ('dev', 'pediatric growth - text', False, None, 'deny.text_rendering'),
    ('dev', 'infection control ltc - text', False, None, 'deny.text_rendering'),
    ('dev', 'allergy rule - text', False, None, 'deny.text_rendering'),
    ('dev', 'calcium poc - text', False, None, 'deny.text_rendering'),
    ('dev', 'referral information - text', False, None, 'deny.text_rendering'),
    ('dev', 'tolac patient safety checklist-text', False, None, 'deny.text_rendering'),
    ('dev', 'transition planning initial asmt - text', False, None, 'deny.text_rendering'),
    ('dev', 'ambulatory vitals, ht, wt - text', False, None, 'deny.text_rendering'),
    ('dev', 'antepartum risk factors - text', False, None, 'deny.text_rendering'),
    ('dev', 'cm psychosocial - text', False, None, 'deny.text_rendering'),
    ('dev', 'functional indep measure scores - text', False, None, 'deny.text_rendering'),
    ('dev', 'transition planning follow-up - text', False, None, 'deny.text_rendering'),
    ('dev', 'lead risk - text', False, None, 'deny.text_rendering'),
    ('dev', 'lipid profile poc - text', False, None, 'deny.text_rendering'),
    ('dev', 'bh psychosocial assessment - text', False, None, 'deny.text_rendering'),
    ('dev', 'birth plan-text', False, None, 'deny.text_rendering'),
    ('dev', 'steadi fall risk - text', False, None, 'deny.text_rendering'),
    ('dev', 'urgent care intake - text', False, None, 'deny.text_rendering'),
    ('dev', 'ambulatory quick intake - text', False, None, 'deny.text_rendering'),
    ('dev', 'transfer note', False, None, None),
    ('dev', 'enhanced note', True, 'note.enhanced', None),
    ('dev', 'cardiology office clinic note', True, 'note.office_clinic', None),
    ('dev', 'urology office clinic note', True, 'note.office_clinic', None),
    ('dev', 'family medicine office clinic note', True, 'note.office_clinic', None),
    ('dev', 'progress note generic', True, 'note.progress', None),
    ('dev', 'wound care progress note', True, 'note.progress', None),
    ('dev', 'neurology progress note', True, 'note.progress', None),
    ('dev', 'cardiology progress note', True, 'note.progress', None),
    ('dev', 'oncology progress note', True, 'note.progress', None),
    ('dev', 'progress notes', True, 'note.progress', None),
    ('dev', 'progress note', True, 'note.progress', None),
    ('dev', 'genetic progress note', True, 'note.progress', None),
    ('dev', 'gynecology progress note', True, 'note.progress', None),
    ('dev', 'cardiothoracic progress note', True, 'note.progress', None),
    ('dev', 'depart summary', True, 'vs.summary', None),
    ('dev', 'inpatient clinical summary', True, 'vs.summary', None),
    ('dev', 'ambulatory clinical summary', True, 'vs.summary', None),
    ('dev', 'encounter summary', True, 'vs.summary', None),
    ('dev', 'discharge summary', True, 'vs.summary', None),
    ('dev', 'ccd document', True, 'vs.ccd', None),
    ('dev', 'summary of care', True, 'vs.summary_of', None),
    ('dev', 'summary of episode note', True, 'vs.summary_of', None),
    ('dev', 'other', False, None, None),
    ('dev', 'error', False, None, None),
    ('dev', 'masked', False, None, None),
    ('dev', 'education note', False, None, 'deny.education'),
    ('dev', 'periop patient education', False, None, 'deny.education'),
    ('dev', 'waveform strip', False, None, None),
    ('dev', 'consent forms', False, None, None),
    ('dev', 'patient letter', False, None, None),
    ('dev', 'radiology reports', False, None, 'deny.diagnostic'),
    ('dev', 'insurance card', False, None, None),
    ('dev', 'advance directive documents', False, None, None),
    ('dev', 'diagnostic imaging study', False, None, 'deny.diagnostic'),
    ('dev', 'referral letter', False, None, 'deny.referral'),
    ('dev', 'hipaa privacy documents', False, None, None),
    ('dev', 'patient personal advance care plan', False, None, None),
    ('dev', 'transition of care referral outbound', False, None, 'deny.referral'),
    ('dev', 'ambulatory patient education', False, None, 'deny.education'),
    ('dev', 'provider letter', False, None, None),
    ('dev', 'surgical pathology report', False, None, 'deny.pathology'),
    ('dev', 'certification id', False, None, None),
    ('dev', "driver's license", False, None, None),
    ('dev', 'polst or post', False, None, None),
    ('dev', 'cancer staging documentation', False, None, None),
    ('dev', 'xr knee 3 views left', False, None, 'deny.diagnostic'),
    ('dev', 'billing authorizations', False, None, None),
    ('dev', 'reminders', False, None, None),
    ('dev', 'sleep study', False, None, None),
    ('dev', 'anatomic pathology', False, None, 'deny.pathology'),
    ('dev', 'admission criteria note', False, None, 'deny.admission_criteria'),
    ('dev', 'pathology consultation', False, 'note.consult', 'deny.pathology'),
    ('dev', 'bd bone density dexa app skeleton', False, None, None),
    ('dev', 'ct abdomen w/ contrast', False, None, 'deny.diagnostic'),
    ('dev', 'ct pelvis w/o contrast', False, None, 'deny.diagnostic'),
    ('prod', 'encounter summary', True, 'vs.summary', None),
    ('prod', 'ccd document', True, 'vs.ccd', None),
    ('prod', 'discharge summary', True, 'vs.summary', None),
    ('prod', 'practice clinical summary', True, 'vs.summary', None),
    ('prod', 'practice visit summary', True, 'vs.summary', None),
    ('prod', 'practice patient summary', True, 'vs.summary', None),
    ('prod', 'inpatient patient summary', True, 'vs.summary', None),
    ('prod', 'progress notes', True, 'note.progress', None),
    ('prod', 'primary care office note', True, 'note.office_clinic', None),
    ('prod', 'bariatric surgery office visit note', True, 'note.office_clinic', None),
    ('prod', 'urgent care office clinic note', True, 'note.office_clinic', None),
    ('prod', 'telephone encounter', True, 'note.telephone', None),
    ('prod', 'history and physical', True, 'note.hp', None),
    ('prod', 'h&p', True, 'note.hp_abbrev', None),
    ('prod', '*history & physical', True, 'note.hp', None),
    ('prod', 'ed notes', True, 'note.ed', None),
    ('prod', 'ed provider notes', True, 'note.ed', None),
    ('prod', 'op note', True, 'note.operative', None),
    ('prod', 'op note - complete', True, 'note.operative', None),
    ('prod', 'upper gi endo report', True, 'note.operative', None),
    ('prod', 'operative report', True, 'note.operative', None),
    ('prod', 'operative note', True, 'note.operative', None),
    ('prod', 'procedure note', True, 'note.operative', None),
    ('prod', 'follow up note', True, 'note.follow_up', None),
    ('prod', 'phone msg', False, None, None),
    ('prod', 'patient instructions', False, None, 'deny.instructions'),
    ('prod', 'discharge instructions', False, None, 'deny.instructions'),
    ('prod', 'pre-procedure instructions', False, None, 'deny.instructions'),
    ('prod', 'anesthesia preprocedure evaluation', False, None, 'deny.anesthesia'),
    ('prod', 'anesthesia postprocedure evaluation', False, None, 'deny.anesthesia'),
    ('prod', 'anesthesia procedure notes', False, 'note.operative', 'deny.anesthesia'),
    ('prod', 'nursing note', False, None, 'deny.nursing'),
    ('prod', 'nursing narrative note', False, None, 'deny.nursing'),
    ('prod', 'ed note nursing', False, 'note.ed', 'deny.note_nursing'),
    ('prod', 'plan of care', False, None, None),
    ('prod', 'cdu treatment plan', False, None, None),
    ('prod', 'result encounter note', False, None, None),
    ('prod', 'diagnostic imaging study', False, None, 'deny.diagnostic'),
    ('prod', 'laboratory report', False, None, 'deny.diagnostic'),
    ('prod', 'lab report', False, None, 'deny.diagnostic'),
    ('prod', 'imaging report', False, None, 'deny.diagnostic'),
    ('prod', 'bravo report', False, None, None),
    ('prod', 'or surgeon', False, None, None),
    ('prod', 'intraoperative report', False, None, None),
    ('prod', 'procedures', False, None, None),
    ('prod', 'insurance', False, None, None),
    ('prod', 'patient education document', False, None, 'deny.education'),
    ('prod', 'pre-cert information - form', False, None, None),
    ('prod', 'bariatric intake and history-form', False, None, None),
    ('prod', 'practice intake and history - form', False, None, None),
    ('prod', 'consent to discuss care & treatment', False, None, None),
    ('prod', 'uc intake and history (practice) - form', False, None, None),
    ('prod', 'annual consent for treatment', False, None, None),
    ('prod', 'transfer note', False, None, None),
    ('prod', 'other', False, None, None),
    ('prod', '', False, None, None),
    ('prod', None, False, None, None),
)

DEV_LABELS = tuple(r for r in LABEL_TABLE if r[0] == "dev")
PROD_LABELS = tuple(r for r in LABEL_TABLE if r[0] == "prod")
